// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2228.VisionSandbox2020.subsystems;


import org.usfirst.frc2228.VisionSandbox2020.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class RobotConstants extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final int DIGITAL_IO_0 = 0;
    public static final int DIGITAL_IO_1 = 1;
    public static final int DIGITAL_IO_2 = 2;
    public static final int DIGITAL_IO_3 = 3;
    public static final int DIGITAL_IO_4 = 4;
    public static final int DIGITAL_IO_5 = 5;
    public static final int DIGITAL_IO_6 = 6;
    public static final int DIGITAL_IO_7 = 7;
    public static final int DIGITAL_IO_8 = 8;
    public static final int ANALOG_INPUT_0 = 0;
    public static final int ANALOG_INPUT_1 = 1;
    public static final int ANALOG_INPUT_2 = 2;
    public static final int ANALOG_INPUT_3 = 3;
    public static final int PCM_PORT_0 = 0;
    public static final int PCM_PORT_1 = 1;
    public static final int PCM_PORT_2 = 2;
    public static final int PCM_PORT_3 = 3;
    public static final int PCM_PORT_4 = 4;
    public static final int PCM_PORT_5 = 5;
    public static final int PCM_PORT_6 = 6;
    public static final int PCM_PORT_7 = 7;
    public static final int PWM_PIN_0 = 0;
    public static final int PWM_PIN_1 = 1;
    public static final int PWM_PIN_2 = 2;
    public static final int PWM_PIN_3 = 3;
    public static final int PWM_PIN_4 = 4;
    public static final int PWM_PIN_5 = 5;
    public static final int PWM_PIN_6 = 6;
    public static final int PWM_PIN_7 = 7;
    public static final int PWM_PIN_8 = 8;
    public static final int PWM_PIN_9 = 9;
    public static final int RIGHT_FRONT_MOTOR = 11;
    public static final int RIGHT_BACK_MOTOR = 12;
    public static final int LEFT_FRONT_MOTOR = 13;
    public static final int LEFT_BACK_MOTOR = 14;
    public static final int PIGEON_IMU_CAN_ID = 61;
    public static final int CANIFIER_CAN_ID = 62;
    public static final int LEFT_DISTANCE_SENSOR_ID = 1;
    public static final int RIGHT_DISTANCE_SENSOR_ID = 2;
    public static final int RELAY_PIN_0 = 0;
    public static final int RELAY_PIN_1 = 1;
    public static final int RELAY_PIN_2 = 2;
    public static final int RELAY_PIN_3 = 3;
    public static final double VISION_TARGET_TOLERANCE_IN_INCHES = 1.0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public RobotConstants() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

